### ISSUE TITLE
transcode(::Type{CodecZlib.GzipCompressor}, ::String) is ambiguous on v0.9.12

### ISSUE THREAD

**Issue by felipenoris** [JuliaIO/TranscodingStreams.jl#139]
Hello! I'm getting this error after updating TranscodingStreams to v0.9.12.

```julia
(@v1.7) pkg> add CodecZlib
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [944b1d66] + CodecZlib v0.7.1
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [944b1d66] + CodecZlib v0.7.1
  [3bb67fe8] + TranscodingStreams v0.9.12

julia> import CodecZlib

julia> CodecZlib.transcode(CodecZlib.GzipCompressor, "hey ya")
ERROR: MethodError: transcode(::Type{CodecZlib.GzipCompressor}, ::String) is ambiguous. Candidates:
  transcode(T, src::String) in Base at c.jl:291
  transcode(::Type{C}, args...) where C<:TranscodingStreams.Codec in TranscodingStreams at /home/fnoro/.julia/packages/TranscodingStreams/5yQuA/src/transcode.jl:33
Possible fix, define
  transcode(::Type{C}, ::String) where C<:TranscodingStreams.Codec
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

**Comment by felipenoris** [comment]
As a workaround, one can use:

```julia
julia> CodecZlib.transcode(CodecZlib.GzipCompressor, "hey ya")
26-element Vector{UInt8}:
 0x1f
 0x8b
 0x08
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x03
 0xcb
 0x48
 0xad
 0x54
 0xa8
 0x4c
 0x04
 0x00
 0x2e
 0xee
 0x85
 0xee
 0x06
 0x00
 0x00
 0x00
```

**Comment by bauglir** [comment]
This appears to be caused by changes introduced in #136, specifically [this signature change](https://github.com/JuliaIO/TranscodingStreams.jl/pull/136/files#diff-070b662fbaa87728d904ec4673449682c5decc1c673b8e5bee249981180de0fbR33).

Although passing a string directly as the second argument to `transcode` does not appear to be documented as [a valid API in this package's README](https://github.com/JuliaIO/TranscodingStreams.jl/blob/3583abe134fac62f38fc26c43e51814bf4d38096/README.md?plain=1#L52-L56). All the linked codec packages, like the mentioned [`CodecZLib`](https://github.com/JuliaIO/CodecZlib.jl/blob/f9fddaa28c093c590a7a93358709df2945306bc7/README.md?plain=1#L36-L39), document that passing a string should work.

Was the removal of this API intentional? If so the release v0.9.12 release should probably have been a minor release instead of a patch release. Mostly looking for an answer as to whether this is something that consuming packages should update or whether the ambiguity will be/should be resolved here. I'm not sure if the splatted `args` can be typed to resolve the ambiguity.
